WIP.

Get just the glyphs your site needs from a font.

Example use case:

You have: a TTF, OTF, EOT, SVG, WOFF OR WOFF2 font.

You want: a tiny subset of the glyphs in all or some subset of those formats.

For example, Font Awesome is awesome, but it's huge:

#+begin_example
$ du -h ./*
108K	FontAwesome.otf
72K	fontawesome-webfont.eot
360K	fontawesome-webfont.svg
140K	fontawesome-webfont.ttf
84K	fontawesome-webfont.woff
68K	fontawesome-webfont.woff2
#+end_example

That's a big download if you just want one or two glyphs.

All you need to know is the unicode codepoints of the glyphs you want to keep,
everything else will be discarded.

There are a bunch of web services that can do this for you, but I wanted
something more programmatic.

Strictly speaking, you don't have to do any crushing.  If you leave
=config.glyphs= undefined only conversions will take place.

TTF is used as an intermediary for all conversions.

* Special thanks

  Really this is just a convenience wrapper around a bunch of other tools.  If
  this project is cool it's because these projects exist:

- [[https://github.com/kekee000/fonteditor-core][fonteditor-core]]
  I can't read Chinese but I think it's the backend for
  [[http://font.baidu.com/editor/index-en.html][Baidu's online font editor]].
- [[https://github.com/google/woff2][woff2]]
  An awesome woff2 encoder/decoder.
- [[https://github.com/nfroidure/ttf2woff2][ttf2woff2]]
  This project is a Node wrapper around Google's
  [[https://github.com/google/woff2][woff2]] project.  It only allows for
  encoding (I wanted to be able to encode and decode), but I reused a lot of the
  code for the woff2 wrapper!
